development:
  adapter: postgresql
  encoding: utf8
  database: chat_ben_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: chat_ben_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: chat_ben_production
  pool: 5
  username:
  password:
